apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-imagepullsecrets
  annotations:
    policies.kyverno.io/description: >-
      Pod need to be authenticated by using imagePullSecrets which created in bootstrap.
      This policy will running in background to add the imagePullSecrets to the new pods.
spec:
  # mutateExistingOnPolicyUpdate: true
  rules:
    - name: add-imagepullsecrets
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - devsecops
      mutate:
        patchStrategicMerge:
          spec:
            imagePullSecrets:
            - name: phidp-image-cred
