apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-imagepullsecrets
spec:
  # mutateExistingOnPolicyUpdate: true
  rules:
    - name: add-imagepullsecrets
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - devsecops
      mutate:
        patchStrategicMerge:
          spec:
            imagePullSecrets:
            - name: phidp-image-cred
