apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-image-pull-secret-pods
spec:
  # mutateExistingOnPolicyUpdate: true
  rules:
    - name: add-image-pull-secret-pods
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - devsecops
      mutate:
        patchesJson6902: |-
          - path: "/spec"
            op: add
            value: imagePullSecrets
          - path: "/spec/imagePullSecrets/-"
            op: add
            value: {"name":"phidp-image-cred"}
