apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-secrets-accross-namespace
spec:
  generateExistingOnPolicyUpdate: true
  rules:
  - name: generate-blogsecret
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      kind: Secret
      apiVersion: v1
      name: phidp-image-cred
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        name: phidp-image-cred
        namespace: argocd
