apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-secrets
  annotations:
    policies.kyverno.io/description: >-
      This policy will prevent action of deleting the secrets
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: protect-blogsecret
      match:
        any:
        - resources:
            kinds:
              - Secret
            names:
              - phidp-image-cred
            namespaces:
              - kyverno
      exclude:
        any:
        - clusterRoles:
          - cluster-admin
        - subjects:
          - name: kyverno
            kind: ServiceAccount
            namespace: kyverno
      preconditions:
        all:
        - key: "{{ request.operation }}"
          operator: AnyIn
          value:
          - DELETE
      validate:
        message: "This Secret is protected and may not be deleted."
        deny: {}
