apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: toolchain
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /
    prometheus.io/port: '8080'
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8080
    nodePort: 32001