
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  storageClassName: local-storage
  claimRef:
    name: jenkins-pvc
    namespace: toolchain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpression:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-node01
---
apiVersion: v1
kind: PerssistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: toolchain
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  
